### ISSUE TITLE
图源搜索问题

### ISSUE THREAD

**Issue by czhash** [xplusky/MoeLoaderP#20]
请问大佬这里的url参数可改吗？因为我发现默认会带一个rating:safe的参数，也就是自带过滤了，所以没法搜索出所有图片
![微信截图_20230705185833](https://github.com/xplusky/MoeLoaderP/assets/91898595/f6ed8a01-f417-4d23-92c6-846847e2b2b8)
![微信截图_20230705185819](https://github.com/xplusky/MoeLoaderP/assets/91898595/b2d1841b-438e-4670-8071-e75cfac9e36b)

**Comment by czhash** [comment]
类似的gelbooru之类的也存在这个问题

**Comment by xplusky** [comment]
> 请问大佬这里的url参数可改吗？因为我发现默认会带一个rating:safe的参数，也就是自带过滤了，所以没法搜索出所有图片 ![微信截图_20230705185833](https://user-images.githubusercontent.com/91898595/251130619-f6ed8a01-f417-4d23-92c6-846847e2b2b8.png) ![微信截图_20230705185819](https://user-images.githubusercontent.com/91898595/251130601-b2d1841b-438e-4670-8071-e75cfac9e36b.png)

F8按10次

**Comment by czhash** [comment]
好的，谢谢
